# Use root/example as user/password credentials
version: '3.1'

services:

  mongos:
    container_name: mongos
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ECACHAIN
    ports:
      - "27017:27017"
 
  eca_chain_server:
    build: 
      context: .
      dockerfile: Dockerfile
    image: "eca-chain-server:latest"
    ports:
      - "3000:3000"
 